### PR TITLE
simplify implementation

### PR DESCRIPTION
**Pull request by JoshData**
Hey,

I made a lot of simplifications, which will make it much easier for me to maintain over the long term.

### CODE REVIEW

**Comment by wbt** [comment]
I understand some of the code changes for simplification, but this includes a lot of design changes too, many of which seem like regressions.  A few things that seem pretty iffy:

- The notes area is shorter (left edge matching Likert item) with white area to the left, instead of permitting full-column width editing.
- There is no longer any communication/indication about whether or not the content is being saved or has been autosaved.  The manual save UX is pretty klunky. 
- With thumbs up/down being positioned on the colored bar instead of outside of it, the labels don't seem to make sense in order: "Slightliy [sic] support, moderately support, strongly support" makes sense but then the most extreme is just "support," not clickable, and not appearing to be the most extreme value selectable, as the previous design communicated.  
- The feature enabling users to make notes is completely unknown to logged-out users, while the support/oppose scale is visible with a "You must be logged in to use this feature" Javascript alert.  
- The stars on the support/oppose scale make it easy to confuse this with a star rating scale common on the web (e.g. "I give this bill 5 stars") which is not the right mental model for a Likert item, and shifts the neutral point (e.g. 4 stars is not necessarily mapped on to "neither support nor oppose" in many other settings).  
- As a minor point, the backslash diagonal gradient looks cooler than the vertical previous version but could introduce bias and resulting criticism of any attempt to use this for eliciting accurate perspectives.

**Comment by wbt** [comment]
I can't review this in detail until the evening, but the changes are definitely an improvement! 
I especially like the more compact vertical alignment with emojis.   It kind of gets lost waaay over on the right on the bill text view, though. 
A few initial thoughts on where opportunities for improvement remain:
- I'm not a fan of the notes field now being a modal popover.  At least for me and some others, the common style of note-taking involves a lot of scrolling to view the actual text and copy and pasting from the text, and referencing notes/bill text back and forth...now we're preventing people from being able to read both contemporaneously. 
- I like that it shows when a position has been saved.
- I'm not sure I like purple between red and green; yellow might be better in a traffic light motif - but this is a very minor point in any case and we might want to check a selection in a colorblind view before finalizing.

**Comment by wbt** [comment]
Also, the most extreme positions were previously intentionally just barely overlapping the ends of the bars, which I think could have helped people feel that the strength of their opinions was at least registered in this domain.

**Comment by JoshData** [comment]
Ok I revised the color and side padding a bit:

image

I agree in part with some of your other points, but let's focus on what's essential. I think this gets us to a point where it's valuable to deploy this and get the larger project moving forward. We can always improve it.

**Comment by wbt** [comment]
Thanks for making those tweaks.
I think it's fine to focus on the most important things first, when they're not already solved. 
I mainly don't see why it's valuable to put extra effort into changes that are actually regressions on usability, which seem like a significant step backward from [GovtrackPR#148](https://github.com/govtrack/govtrack.us-web/pull/148), like that notes are now a modal popover and the whole interface moves way over to the right (under Select Language; easy to get lost) on the bill text page.

**Comment by JoshData** [comment]
There were a variety of reasons for the changes, but most came down to having a simpler implementation that stands a higher chance of not breaking. That includes removing auto-save and the icons you added and having fewer page-level elements that are contending for space (=> moving the textarea to a modal). Re-using existing design patterns (e.g. using the fontawesome icons for the likert positions, using modals) is also more likely to produce a clear and accessible (i.e. for visual disability) interface for the end-user compared to inventing new design patterns (a toggleable textarea and autosave). These things have an enormous pay off in reducing the time I spend on maintenance over the next, say, 5 years, so they're a top priority.

**Pull request merged**
